#!/usr/bin/env python3
"""Turn a cluster into a *proposed* knowledge-base change -- never an automatic one.

M2's hard rule (docs/roadmap.md M2): "a cluster becomes a proposed PR against the
project's own invariants.md/constitution.md. Never an automatic edit; a human
approves every change to the knowledge base." So this module only ever writes a
human-readable proposal document. Applying it is a person opening a PR against
their own knowledge repo after reading it.

The proposal's recommendation depends on the dominant verdict:

- dominant `ignored`, with a cited rule  -> reviewers keep surfacing this rule and
  humans keep merging past it. Either the rule is too strict, its severity is too
  high, or the routing that attaches it is too broad. Proposed: review the rule.
- dominant `corrected`, with a cited rule -> reviewers keep disputing findings that
  cite this rule as wrong. The rule may be mis-stated, or it's being applied to
  code it shouldn't. Proposed: re-word the rule or narrow its route.
- dominant `corrected`, no cited rule     -> a recurring false-positive *pattern*
  with no rule behind it. Proposed: add a constitution note steering reviewers off
  this pattern (the demo-project's pr-06 false-positive trap is the archetype).
- dominant `ignored`, no cited rule       -> recurring general-correctness findings
  that get merged past. Weaker signal; proposed only as "spot-check whether these
  were right".

Usage:
  promote.py --ledger <path> [--min-occurrences 3] [--out proposals.md]
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from cluster import cluster, DEFAULT_MIN_OCCURRENCES  # noqa: E402
from record import load_records  # noqa: E402


def recommend(c: dict) -> str:
    dom = c["dominant_verdict"]
    has_rule = bool(c["cited_refs"])
    refs = ", ".join(c["cited_refs"])
    if dom == "ignored" and has_rule:
        return (
            f"Reviewers repeatedly cite **{refs}** and humans repeatedly merge without "
            f"changing the flagged line. Review whether this rule is too strict, its "
            f"severity too high, or the route attaching it to `{c['file_pattern']}` too "
            f"broad. If the rule is correct as stated, no change -- record why here so "
            f"the same cluster doesn't re-surface as new."
        )
    if dom == "corrected" and has_rule:
        return (
            f"Reviewers repeatedly raise findings citing **{refs}** that humans mark "
            f"**wrong**. The rule may be mis-stated, or applied to code it shouldn't be. "
            f"Propose a re-wording of the rule, or narrowing the route that attaches it "
            f"to `{c['file_pattern']}`."
        )
    if dom == "corrected" and not has_rule:
        return (
            f"A recurring false-positive pattern in `{c['file_pattern']}` "
            f"({c['category']}) with no project rule behind it. Propose a short "
            f"`constitution.md` note describing the pattern and why it is *not* a defect, "
            f"so future reviews don't re-raise it."
        )
    return (
        f"Recurring `{c['category']}` findings in `{c['file_pattern']}` that merge past "
        f"unchanged, with no cited rule. Weak signal -- spot-check whether these findings "
        f"were actually correct before deciding anything. If several were right, that is a "
        f"candidate for a *new* invariant, not a relaxation."
    )


def render_proposal(c: dict) -> str:
    lines = [
        f"### {c['file_pattern']} · {c['category']} · {', '.join(c['cited_refs']) or 'no cited rule'}",
        "",
        f"- **Occurrences:** {c['occurrence_count']} distinct PRs "
        f"({', '.join(f'#{p}' for p in c['distinct_prs'])})",
        f"- **Verdicts:** {', '.join(f'{v} ×{n}' for v, n in c['verdict_counts'].items())} "
        f"(dominant: **{c['dominant_verdict']}**)",
        f"- **cluster_key:** `{c['cluster_key']}`",
        "",
        f"**Proposed action.** {recommend(c)}",
        "",
        "<details><summary>signal trail</summary>",
        "",
        "| PR | verdict | signal | anchor | when |",
        "|---|---|---|---|---|",
    ]
    for o in c["occurrences"]:
        lines.append(
            f"| #{o['pr']} | {o['verdict']} | {o['signal']} | "
            f"`{o['file']}:{o['line']}` | {o['ts']} |"
        )
    lines += ["", "</details>", ""]
    return "\n".join(lines)


def render_document(clusters: list) -> str:
    header = [
        "# Proposed knowledge-base changes",
        "",
        "Generated by `engine/ledger/promote.py` from the feedback ledger. **Nothing "
        "here is applied automatically.** Each block is a pattern seen across several "
        "independent PRs; a human decides whether the project's `invariants.md` / "
        "`constitution.md` should change, and opens that PR themselves.",
        "",
    ]
    if not clusters:
        return "\n".join(header + ["_No clusters currently meet the occurrence threshold._", ""])
    return "\n".join(header + [render_proposal(c) for c in clusters])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ledger", required=True)
    ap.add_argument("--min-occurrences", type=int, default=DEFAULT_MIN_OCCURRENCES)
    ap.add_argument("--out", default=None, help="write the proposal doc here; else stdout")
    args = ap.parse_args()

    clusters = cluster(load_records(args.ledger), min_occurrences=args.min_occurrences)
    doc = render_document(clusters)
    if args.out:
        Path(args.out).write_text(doc)
        print(f"wrote {len(clusters)} proposal(s) to {args.out}")
    else:
        print(doc)


if __name__ == "__main__":
    main()
